#!/usr/bin/env bash

# #
# # Clone all of whymirror's repos as origin
# #
# repo=8cpj                   ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=blimlimb               ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=bloopsaphone           ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=camping                ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=greg                   ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=hacketyhack            ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=hobix                  ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=hpricot                ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=markaby                ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=metaid                 ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=mixico                 ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=mousehole              ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=parkplace              ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=potion                 ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=redcloth               ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=sheila                 ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=shoes                  ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=syck                   ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=unholy                 ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=TryRuby                ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=required-security-for-tryruby  ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=sandbox                ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=why_sandbox            ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=chirrup                ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=fakeplus               ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=processor              ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=rb_parse_args          ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=skistrap               ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=superredcloth          ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=hoodwinkd              ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=yown                   ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi

# #
# # Mainline
# #
# # git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ;
# # git-rbranch git://github.com/${user}/${repo}.git ;
repo=8cpj                   ; user=drnic           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=blimlimb               ; user=bterlson        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=bloopsaphone           ; user=mental          ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=camping                ; user=camping         ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=greg                   ; user=localhost       ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=hacketyhack            ; user=steveklabnik    ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=hobix                  ; user=hobix           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=hpricot                ; user=ecarnevale      ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=markaby                ; user=joho            ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=metaid                 ; user=dannytatom      ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=mixico                 ; user=rkh             ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=mousehole              ; user=evaryont        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=parkplace              ; user=mattjamieson    ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=potion                 ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=redcloth               ; user=jgarber         ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=sheila                 ; user=wmorgan         ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=shoes                  ; user=shoes           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=syck                   ; user=indeyets        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=unholy                 ; user=devyn           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=TryRuby                ; user=Sophrinix       ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=required-security-for-tryruby; user=Sophrinix ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=sandbox                ; user=parolkar        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=why_sandbox            ; user=parolkar        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=chirrup                ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=fakeplus               ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=processor              ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=rb_parse_args          ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=skistrap               ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )

# #
# # As Mainline
# #
repo=8cpj                   ; user=drnic           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=blimlimb               ; user=bterlson        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=bloopsaphone           ; user=mental          ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=camping                ; user=camping         ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=greg                   ; user=localhost       ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=hacketyhack            ; user=steveklabnik    ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=hobix                  ; user=hobix           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=hpricot                ; user=ecarnevale      ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=markaby                ; user=joho            ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=metaid                 ; user=dannytatom      ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=mixico                 ; user=rkh             ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=mousehole              ; user=evaryont        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=parkplace              ; user=mattjamieson    ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=potion                 ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=redcloth               ; user=jgarber         ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=sheila                 ; user=wmorgan         ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=shoes                  ; user=shoes           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=syck                   ; user=indeyets        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=unholy                 ; user=devyn           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=TryRuby                ; user=Sophrinix       ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=required-security-for-tryruby; user=Sophrinix ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=sandbox                ; user=parolkar        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=why_sandbox            ; user=parolkar        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=chirrup                ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=fakeplus               ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=processor              ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=rb_parse_args          ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )
repo=skistrap               ; user=fogus           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master mainline git://github.com/${user}/${repo}.git ; git checkout --track -b mainline_master mainline/master ; git co master )

# #
# # Other Contributors
# #
repo=bloopsaphone           ; user=aberant         ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=camping                ; user=judofyr         ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=hobix                  ; user=mental          ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=hobix                  ; user=crnixon         ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=hpricot                ; user=olabini         ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=markaby                ; user=spox            ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=metaid                 ; user=evaryont        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=mousehole              ; user=devyn           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=parkplace              ; user=technoweenie    ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=potion                 ; user=lutzky          ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=shoes                  ; user=mental          ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=shoes                  ; user=greatseth       ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=unholy                 ; user=jmkogut         ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=TryRuby                ; user=parolkar        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=sandbox                ; user=Sophrinix       ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=why_sandbox            ; user=Sophrinix       ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=fakeplus               ; user=sspencer        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )

# #
# # Transient heads
# #
repo=markaby                ; user=smtlaissezfaire ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=metaid                 ; user=chneukirchen    ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=mousehole              ; user=joshprice       ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=parkplace              ; user=jeremymcanally  ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=sandbox                ; user=jschoolcraft    ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=superredcloth          ; user=yup             ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=superredcloth          ; user=skwp            ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=hoodwinkd              ; user=robbyrussell    ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=yown                   ; user=iamjwc          ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )

# repo=poignant-guide         ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# repo=poignantguide          ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
repo=poignant-guide         ; user=mislav          ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )
repo=poignantguide          ; user=luigi           ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master ; git status ; git branch )

# # repo=poignant-br            ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# # repo=why-archive            ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# # repo=poignant-br            ; user=carlosbrando    ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master && git pull $user master ; git status ; git branch )
# # repo=why-archive            ; user=steveklabnik    ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master && git pull $user master ; git status ; git branch )
# # repo=why-archive            ; user=binary42        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master && git pull $user master ; git status ; git branch )
# # repo=bumpspark              ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# # repo=myfs                   ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# # repo=railsfs                ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# # repo=wordy                  ; if [ -d ~/ics/projects/whymirror/${repo} ] ; then  echo "exists!" ; else ( cd ~/ics/projects/whymirror/ && git clone git@github-whymirror:whymirror/${repo}.git ) ; fi
# # repo=bumpspark              ; user=yup             ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master && git pull $user master ; git status ; git branch )
# # repo=bumpspark              ; user=fiveruns        ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master && git pull $user master ; git status ; git branch )
# # repo=myfs                   ; user=yup             ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master && git pull $user master ; git status ; git branch )
# # repo=railsfs                ; user=yup             ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master && git pull $user master ; git status ; git branch )
# # repo=wordy                  ; user=yup             ; ( cd ~/ics/projects/whymirror/${repo} && git remote add -f -m master ${user} git://github.com/${user}/${repo}.git ; git checkout --track -b ${user}_master ${user}/master ; git co master && git pull $user master ; git status ; git branch )
